TS_EXTRA_SEARCH_PATHS=(~/projects ~/Projects)
TS_SESSION_COMMANDS=('bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' 'bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' "image-request")
TS_MAX_DEPTH=2
# TS_LOG=source $HOME/.tmux-sessionizer
source $HOME/.tmux-sessionizer
