preload = /home/andy/Downloads/AUS_wallpaper.jpeg
wallpaper {
    monitor = eDP-1
    path = /home/andy/Downloads/AUS_wallpaper.jpeg
}

wallpaper {
    monitor =
    path = /home/andy/Downloads/AUS_wallpaper.jpeg
}
