preload = /home/andy/Downloads/AUS_wallpaper.jpeg
wallpaper {
    monitor = eDP-1
    path = /home/andy/Pictures/daintree_wallpaper.JPG
}

wallpaper {
    monitor =
    path = /home/andy/Pictures/daintree_wallpaper.JPG
}
