TS_EXTRA_SEARCH_PATHS=(~/projects)
TS_SESSION_COMMANDS=('bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' 'bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' "image-request")
# TS_LOG=source $HOME/.tmux-sessionizer
soruce $HOME/.tmux-sessionizer
