set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-a

# spltting
unbind %
bind | split-window -h
# vertical
unbind '"'
bind - split-window -v

# reloading config
unbind r
bind r source-file ~/.tmux.conf

# resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# mouse support
set -g mouse on

# min and max panes
bind -r m resize-pane -Z

set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato' # latte or frappe, macchiato, mocha

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_user "on"



bind-key g display-popup -d "$HOME/scripts" -w 60% -h 60% ./query-llm.sh
bind-key v display-popup -d "#{pane_current_path}"
# set-environment -g PATH "/usr/local/bin:/bin:/usr/bin:/opt/homebrew/bin/:/usr/sbin:/sbin:/bin/zsh"

run-shell "$HOME/.tmux/plugins/tpm/tpm"
set-option -g default-shell /usr/bin/zsh 


bind-key -T copy-mode-vi v send-keys -X begin-selection

